### ISSUE TITLE
treatment of settings in restart 

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#100]
Max, with low priority, can you have a look at the behavior of settings in a restart situation

```
outMCMC = runMCMC(bayesianSetup, settings = settings1)
outMCMC2 = runMCMC(outMCMC = settings2)
```

I think if settings are not provided, the same settings are used, but if I remember correctly, if settings are provided, but not all of the previous settings, then the default is used. So, for example  

settings1 = list(iterations = 20, parB = X) 
settings2 = list(iterations = 30)

then, I think, settings2 will have parB in default and not X. Can you check that this is indeed how it is programmed, and if so, I wonder if we should throw a warning.

Alternatively, we could of course take settings1 as new defaults, instead of the global defaults? That would probably require a new argument customDefaults to the applySettingsDefault function, but this seems quite doable / stable to me.

**Comment by MaximilianPi** [comment]
If Restart == True, the new settings are given to the applySettingsDefault() function and the settings not mentioned are set to default (parB in your example) but the new settings will be ignored because the sampler takes the settings from the previous one, only iterations is updated:
```
    settings <- applySettingsDefault(settings = settings, sampler = settings$sampler, check = TRUE)
    mcmcSampler <-  sampleMetropolis(mcmcSampler = previousMcmcSampler, iterations = settings$iterations) 

```
It's only the case for Metropolis, AM, DR and Dram samplers because for the other samplers settings are given to them and the old settings are ignored
```
out <- DE(bayesianSetup = previousMcmcSampler, settings = settings)
```
So how do you want to solve it? Of course, we have to change the Metropolis sampler, either we update the settings (previousMcmcSampler$settings <- settings) or we add an additional argument "settings" parameter as the other samplers have.

**Comment by MaximilianPi** [comment]
786e7cf664904eaa8c918071edf7b36a5e19dd95

**Comment by MaximilianPi** [comment]
Previous settings are now treated as default for the restart
90e548e2021b6d0315f345254a7d9eabb6d2eb9a
