### ISSUE TITLE
Sampling a normal distribution mean = mu, sigma = s

### ISSUE THREAD

**Issue by phisanti** [florianhartig/BayesianTools#107]
#I have been playing around with the package for a couple of days and I find it amazing. Really promising. However, I do not completely understand it yet. In order to progress, I would like to propose the simplest example: sample from a normal distribution mean mu and standard deviation sigma. If I have get it correctly, the model should be stated like this:
```
`
n <- 10
x <-  rnorm(n=n, mean=15, sd=1)

# Likelyhood
ll<- function(param){
  ll = dnorm(x,  param[1], param[2], log = T)
  return(sum(ll))  
}

setup <- createBayesianSetup(ll, lower = c(5,  0), upper = c(20,10))

settings = list(iterations = 15000,  message = FALSE)
out <- runMCMC(bayesianSetup = setup, settings = settings)
plot(out)
```
`
From here, I don't have a clear idea on how the data is taken by the function as it is not explicitly stated, and I don't easily get the output because it is labeled as par1 and par2. 

In addition, I would like know how to add a normally distributed prior. However, it seems the prior, as described in the example, requires two values (`d1, d2`), and it is obscure why, and what does each value. A clear explanation would really help me.
```

density = function(par){
  d1 = dunif(par[1],
             -2,2, log =TRUE)
  d2 = dnorm(par[2], 
             mean= m, # Mean m
             sd = s,  # Standard deviation s
             log =TRUE)
  return(d1 + d2)
}

# The sampling is optional but recommended because the MCMCs can generate automatic starting
# conditions if this is provided
sampler = function(n=1){
  d1 = runif(n, -2,2)
  d2 = rnorm(n, mean= m, sd = s)
  return(cbind(d1,d2))
}
prior <- createPrior(density = density, sampler = sampler, 
                     lower = c(-1,-5), upper = c(1,5), best = NULL)
```

Kind regards

**Comment by MaximilianPi** [comment]
So first of all, in your example you have n = 10 observations and now you want to approximate the two parameters mean = 15 and sd = 1 because they are unknown in a realistic problem. 
The ll function calculates the likelihood of your data x under the given par[1] (=mean) and par[2]. In the package the global env is given to the function so your ll function always has the data x. (Is this the answer to your question about how the data is taken by the function?
In the first part your prior(possible values for mean and sd, par[1] and par[2]) is taken from an uniform distribution. To take them from a normal distribution you have to set up your own density and sampler function (to sample the mean and sd values, not the actual observed data x!)


`
x <-  rnorm(n=n, mean=15, sd=1)
# Sample mean(=par[1]) and sd(=par[2]) values from a normal distribution
sampler <- function(n=1){
  d1 <- rnorm(n, mean = 15, sd = 10)
  d2 <- rnorm(n, mean = 1, sd = 5)
  return(cbind(d1,d2))
}
density <- function(par){
  d1 <- dnorm(par[1],  mean = 15, sd = 10, log = T)
  d2 <- dnorm(par[2], mean = 1, sd = 5, log = T)
  return(d1+d2)
}
prior <- createPrior(density = density, sampler = sampler)

# calculate the ll of the given data x under the parameters par[1] and par[2]
ll <- function(par){
  sum(dnorm(x, par[1], par[2], log = T))
}
prior <- createPrior(density = density, sampler = sampler)
settings = list(iterations = 1000)
out <- runMCMC(bayesianSetup = setup, settings = settings)
`

**Comment by florianhartig** [comment]
I made a few Max answer to clarify things. Hope this helps.
