### ISSUE TITLE
likelihood class structure

### ISSUE THREAD

**Issue by TankredO** [florianhartig/BayesianTools#115]
In contrast to the prior functions where each "special" function (e.g. createUniformPrior) calls the base function "createPrior" to construct a object of class prior, "special" likelihood functions (e.g. likelihoodIidNormal) do not call createLikelihood but just return a function.

Should we standardize this?

**Comment by florianhartig** [comment]
I think this is OK, because the idea would be that a user would use the special likelihoods inside a custom likelihood density fucntion, so e.g. 

```
likelihood <- function(par){
  pred = model(par)
  ll = likelihoodAR1(pred, obs)
  return(ll)
}
```

and from that call createLikelihood(likelihood), or, more likely, use this directly in the BayesianSetup, as in 

`setup = createBayesianSetup(likelihood)`

which then internally calls createLikelihood. The latter is I think the most common use case, I think in the examples we never called createLikelihood directly, as there are few advantages compared to calling it directly

**Comment by TankredO** [comment]
This seems solved to me, I will close this issue.
