### ISSUE TITLE
Gelman Diagnostics for population MCMCs (DE, DREAM) indicates convergences, trace plot does not

### ISSUE THREAD

**Issue by fkrauer** [florianhartig/BayesianTools#197]
Hi Florian

I am using BT since 2 years, but I have a problem since the last update:

The gelmanDiagnostics() would indicate convergence for some parameters, but the plot() does not look like they converged (for example param bhv or K)
```
Potential scale reduction factors:

      Point est. Upper C.I.
bhp         1.00       1.00
bhv         1.00       1.01
bvh         1.00       1.01
ca          1.00       1.01
da          1.05       1.16
delta       1.04       1.06
Ihp0        1.00       1.00
Ihs0        1.05       1.08
Iv0         1.18       1.53
k           1.00       1.00
K           1.00       1.00
rho         1.08       1.14
sigma       1.00       1.00

Multivariate psrf
1.18
````

I am now using BayesianTools_0.1.7 and the DEzs sampler. Has anyone else had this problem? The trace obviously needs burn-in, but there is no stable segment for some of the parameters. This has not happened before. 

Thanks

![trace1](https://user-images.githubusercontent.com/36159611/76074317-74a8a380-5f9b-11ea-92da-d9711a1240f1.jpeg)
![trace2](https://user-images.githubusercontent.com/36159611/76074320-75d9d080-5f9b-11ea-8ca1-a238883f1d22.jpeg)

**Comment by florianhartig** [comment]
Hi Fabienne, 

I assume that this is done with a population MCMC, such as DEzs?

The issue is that, although Cajo te Braak proved in a paper that DE etc. sample independent AFTER the burn-in, they do not sample independent during the burn-in ... you can see this very clearly in your plots. 

We therefore warn in the help somewhere that you shouldn't use the Gelman Diagnostic on a singe DEzs, or you have to remove burn-in. So, for the entire DE and DREAM family

* either remove burn-in visually, and then calculate Gelman Rubin only after the burn-in
* or (better) run 3 independent MCMCs, and ideally remove burn-in as well (because Gelman-Rubin should be calculated after the burn-in in either case)

Cheers,
Florian

**Comment by fkrauer** [comment]
Okay, that makes sense. I will assess convergence visually first, remove burn-in and then check Gelman Diagnostics. Thanks for the explanation. Cheers, Fabienne

**Comment by florianhartig** [comment]
Yeah, but I would also definitely run at least 2 separate samplers.

**Comment by fkrauer** [comment]
I thought that DEzs runs 3 chains per default (even if I have nrChains = 1 in the settings)? At least that was the case in previous versions, but maybe this has changed?

**Comment by florianhartig** [comment]
Yes, they have 3 chains, but with the nrChains, we count the number of samplers that are run. The internal chains are a separate parameter. 

If you set nrChains = 3, you will have 9 chains. In retrospect, we should have named the argument nrMCMCs, you are not the first one to be confused about this.

**Comment by fkrauer** [comment]
oh I see, then I have been doing it wrong all this time...will change nrChains=2. Thanks
