### ISSUE TITLE
No longer on CRAN

### ISSUE THREAD

**Issue by stineb** [florianhartig/BayesianTools#243]
Will BayesianTools continue to be maintained to be made available on CRAN? 

We love this package, use it, and hope to be able to use it also in the future. Thanks for your great efforts, @florianhartig !

**Comment by florianhartig** [comment]
Hello,

yes, I assume that BT will be back on CRAN soon.

The package is currently removed because of a new CRAN policy regarding the format of the help #240, which I fixed, but now I have another diffuse problem #244 which prevents me from passing the incoming CRAN checks and upload the fix.

As soon as this is fixed, BT will be back on CRAN.

AFAIK, there is no "technical" problem with the package, so you can either use the last CRAN version (download from CRAN by hand, install as ZIP), or you can install the latest version via GitHub as explained here https://github.com/florianhartig/BayesianTools

Best
Florian

**Comment by florianhartig** [comment]
That took a bit longer, but now solved #244 and BT is back on CRAN https://cran.r-project.org/web/packages/BayesianTools/index.html!
