### ISSUE TITLE
Error message after increasing the number of iterations

### ISSUE THREAD

**Issue by yihsiu** [florianhartig/BayesianTools#32]
Hi Florian,

First I'd very like to thank you for creating this package. It's powerful and helps my current project a lot! I really like it. 

But I receive this error message while I run my code and I wonder if I could ask for a hand on it. 

I am currently running a hierarchical Bayesian model based on DRAM sampler. The code is running ok when I only test it with 5000 iterations. But it returns below error when I increases the number of iterations to 70000:

```
> **Error in proposal[j, ] = mcmcSampler$proposalGenerator$returnProposal(x = mcmcSampler$current,  : 
>   number of items to replace is not a multiple of replacement length
> In addition: Warning message:
> In x + move * scale :
>   longer object length is not a multiple of shorter object length**
```

As I couldn't quite understand what this error message means, would you mind helping me on this? 

Thank you very much in advance!

Best wishes
Yi-Hsiu

**Comment by florianhartig** [comment]
Hi yihsiu, 

thanks for reporting this. It's hard to say what the problem is without seeing your code. Would you mind posting your code + data here, or if you feel uncomfortable with this, send it to me via email? 

Best,
F

**Comment by yihsiu** [comment]
Hi Florian,

Thanks very much for reply. Since it's a long code, it'd be more readable in the email. I will send you an email in a wee while. 

Thanks again!

Best wishes
Yi-Hsiu

**Comment by florianhartig** [comment]
The issue was that, in the script, the adaptation start was set before the end of the burnin.

The way the sampler is currently programmed, this is not possible, because the adaptation is based on the recorded chain. I have now added checks so that the user is warned if such a settings is attempted in https://github.com/florianhartig/BayesianTools/commit/20f489c9dc8c7087091370415165fe972d8aa64a

Yi-Hsiu, I've now also rerun the sampler, once this is removed all seems to work fine. 

A general note: the burnin setting is intended for saving memory. If you don't have a memory problem, better not touch it, there is no harm in recording the whole chain. All later functions in BayesianTools have the option start = XX to discard the desired amount of burnin from the calculations / plots.
