### ISSUE TITLE
Extend marginal plots 

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#66]
a) extend vioplots to show also prior

b) option to have histograms instead of vioplots

**Comment by TankredO** [comment]
I am not sure what is the best way to get the prior distribution/"values". I think it might be best to get the values directly from the prior density, but this is not always possible since the priors do not necessarily have upper and lower bounds specified. So we don't know the range where it is allowed to draw from the density. Is this correct?
Another way would be to draw from the prior via the sampler functions. This is quite inefficient for complicated priors, but I don't know if this is even a problem for a plotting function. 
What do you think about this?

**Comment by TankredO** [comment]
daba6c98d36c1b0aa3b66cc0df267085ac3c1d5b

**Comment by TankredO** [comment]
610cdc6a483012c26b93e1b269bc30e70fb4c2a1
