### ISSUE TITLE
DE, DEzs, DREAM, DREAMzs need at least two full MCMC iterations

### ISSUE THREAD

**Issue by lionel68** [florianhartig/BayesianTools#68]
Here is an issue that arise when using runMCMC with one of the above-mentioned samplers (no issues running with Metropolis or SMC). Running the following code:
```
library(BayesianTools)

obs <- runif(30,-2,2)

lik <- function(par){
  pred <- rnorm(30,par[1],par[2])
  diff <- pred - obs
  llValues <- dnorm(diff, sd = par[3], log = TRUE)  
  return(sum(llValues))
}

bTMP <- createBayesianSetup(lik,lower=rep(1,3),upper=rep(10,3))

settings <- list(iterations = 2, nrChains = 1)
runMCMC(bayesianSetup = bTMP, settings = settings) #this does not work
```
returns: 
```
Error in `[<-`(`*tmp*`, (M0 + (counterZ * Npop) + 1):(M0 + (counterZ +  : 
  subscript out of bounds
```

**Comment by Lionel68** [comment]
And here is my sessionInfo():
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_BE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_BE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_BE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BayesianTools_0.1.3

**Comment by florianhartig** [comment]
Hi Lionel,

thanks for reporting this. Yes, I can confirm this behavior. Without looking into details, I'd hazard a guess that the population MCMCs need at least 2 full iterations because of Rs annoying habit of collapsing matrices into vectors when one dimension is not extended (in your code, you are requesting two iterations, but you have to remember that the DEzs that you run has 3 internal chains, so what you do here rounds the 2 to 3 and then basically runs 1 DEzs cycle). If you set iterations >3, we have >1 iterations -> the sampler works. 

I guess we could fix this in the code, but I don't really see why a user should want to run such a small number of iterations (I assume you were trying out if the sampler works, but you might just as well have run 6 iterations).

So, I'd think it's best to just throw an error that iterations/internalChains should be >1

Tankred, could you 

- have a short look just to make sure that what I think is happening is indeed happening

- confirm that this applies to all DE and DREAM, but not the Twalk or the other samplers,

- and then add a stop statement in the applySettingsDefault function to throws an error if the sampler is in the list, and iterations / internalChains is <2?

**Comment by lionel68** [comment]
Hi Florian,
Ok thanks for clarifying this and glad to hear that it is only due to an R behavior. I was indeed testing my code and using low number of iterations to avoid too much waiting time.

**Comment by TankredO** [comment]
Unfortunately, we can not easily check for this error in applySettingsDefault, since we can not see the number of internal chains there. We could calculate it again (or rather before it is calculated in the mcmc functions) in applySettingsDefault, but I think that would be quite confusing. Maybe it would be better to check for this in the corresponding mcmc functions?

**Comment by TankredO** [comment]
8994a06e3692695750ae08f7ecb5b4460f4316d0
Added a check for this inside the mcmc functions
