### ISSUE TITLE
How to set MCMC initial values & precision problems (- Inf in likelihood)

### ISSUE THREAD

**Issue by yihsiu** [florianhartig/BayesianTools#69]
Hi, I am a JAGS user but starting to use BayesianTools more, as it's really helpful when dealing with more complicated models such as models with hidden states or models that require customized likelihood functions! Thanks for providing more options for running Bayesian analysis! 

I have few questions about settings and an issue I met while trying my models with BayesianTools. I wonder could I ask them here? 

1) I was just wondering if I can also specify initial value for each parameter in each chain in BayesianTools as in JAGS?  (sorry if it's a dumb question, I know BayesianTools probably works in a different way than JAGS...)

2) When I was trying BayesianTools for one of my models, there were a few times it showed _-Inf_ for all the chains (I used DEzs) then quickly skipped through all the iterations and terminated. However, as the likelihood function I set was unlikely to return -Inf and the issue only come up sometimes even when running the same model, I was just wondering is there a lower limit for likelihood value that BayesianTools can take? 

 Thank you very much!  

Best wishes
Yi-Hsiu

**Comment by florianhartig** [comment]
Hi Yi-Hsiu,

glad you find the package helpful. About your questions: 

1. yes, see the help of the individual samplers. all starting values can be set by hand, although I think the default of starting from the prior is acceptable for most scenarios

2) yes, you can change the parameters, just provide new settings. Note, however, that if you provide a settings object, all parameters that are not included there will be set on default, even if they were set before (not sure if we should change this ... )

3) BT has the normal R limits for machine precision, unlike to hit this with log likelihoods if we programmed everything right. Are you sure your likelihood is unlikely to return -Inf when sampling parameters from the prior? Because this is what's happening in the DEzs to construct the initial z-matrix. Should be easy to check this by including a print statement in your likelihood, to return ll + parameter values. 

If the -Inf in the likelihood is the problem, that would be a case for setting start values (x and z matrix) by hand, with probably with less dispersion than the prior. Actually, with very wide priors, this can also speed up the sampler considerably

**Comment by yihsiu** [comment]
Hi Florian,

Thanks very much for the help. Regarding question 1, I checked the help of the individual samplers and found it was in help document already. Sorry for still asking it.  

I have tried new run with manually set initial values for each chain, the -Inf issue seem to stop coming up. Maybe those -Inf  were caused by the two rather flat priors in my model, the flat priors made it difficult for the program to find proper initial values.  

I am slightly concerned whether it's ok to only set x matrix manually but leave z matrix as NULL (this is what I did), as you mentioned both x and z matrices in the response. From the DEzs paper, it looks like z matrix is like a space to store the states of the chains. I assume it's ok not to specify it when I specify initial matrix. But I was just wondering is z matrix required to input when x matrix is specified manually? 

Best wishes
Yi-Hsiu

**Comment by florianhartig** [comment]
Hi Yi-Hsiu,

about z - yes, and no. During the MCMC iterations, z is filled with previous MCMC steps, but initially, you have to put some values in there to get the algorithm starting. The z matrix is used to generate the proposals via the DE-evolution idea. 

It is definitely OK to set z (there's no "wrong" values for z), and it' up to you how to set them. My general observation is that, if you have very wide priors, initializing Z by sampling from the prior can create inefficiently wide proposals - you see this via low acceptance rates / bad mixing, in extreme case the sampler can even get stuck, because you stay to long at the same values, filling up z, and at some point you don't have enough variability in Z to generate good proposals any more, a vicious cycle. 

So, it's definitely OK and sometimes necessary playing around with Z initialization more peaked than the prior. 

That being said - if the default settings work, just don't touch it!

Best,
Florian
