### ISSUE TITLE
Error message in WAIC when likelihood is not available point-wise

### ISSUE THREAD

**Issue by TankredO** [florianhartig/BayesianTools#83]
In the WAIC function, an error is thrown in the line
```r
pointWiseLikelihood = t(llDensity(x[i,1:nPars], sum = F))
```
```Error in likelihood(x, ...) : unused argument (sum = FALSE)```

when the likelihood density function has no "sum" argument.

**Comment by florianhartig** [comment]
Yes, this correct and not an error, but rather a result of WAIC requiring a likelihood with argument sum, as described in the help.

However, we could maybe improve the error message and refer the user to the WAIC help, where details about the likelihood are explained?

So, I would

- In the BayesianSetup, check if the likelihood has an argument with sum = F via https://stat.ethz.ch/R-manual/R-devel/library/base/html/args.html, and introduce a parameter for that in the setup

- in WAIC, we can then simply query if the likelihood can be returned point-wise, and otherwise throw an error 

- potentially check / adjust help to better inform the user about what to do

**Comment by TankredO** [comment]
0ccbb9ed8d7cb2b515d5aa2a00e916f76b8b7d90
Added checks for point-wise likelihood

75e30e0970106ece1eada1e0b717ef73c26a8664
Adapted test cases to work with the changes

**Comment by florianhartig** [comment]
@MaximilianPi  can you do a final check if this all works and close

**Comment by TankredO** [comment]
Checked and working
