### ISSUE TITLE
Question about multiple chains and parallelism

### ISSUE THREAD

**Issue by woodwards** [florianhartig/BayesianTools#89]
Hi Florian

First, I am very grateful that you've provided this wonderful package. I was a big fan of DREAMzs in Matlab but now I am using R, so this is perfect. I work in agricultural and environmental modelling. I have also used RStan a bit.

I have got BT working on my current model (the model runs as a Fortran DLL and the likelihood is calculated in R), and I successfully parallelised it for 7 cores. I am calibrating with DREAMzs. I have a few questions.

- I noticed only 2 cores are getting used. Is that because my model runs fast enough that the scheduler doesn't need to use more cores? 

- I found the documentation not too clear that some of the samplers have a certain number of internal chains (e.g. DREAMzs startValue = 3), and that iterations is the total across all chains. It took me quite a bit of reading before I came across this information in the documentation. So am I right that the internal chains in DREAMzs are used for the search, but are not independent and therefore not used for convergence testing? And so multiple external (independent) chains are required to calculate the Gelman R statistic?

- Is there any way to control the amount of output from summary(out)?

- This is more of a general question, but do I need a certain number of iterations to calculate the Gelman R statistic? How many? How do you get it to ignore the burnin iterations? 

I am loving BT! 

Simon

**Comment by florianhartig** [comment]
Hi Simon,

thanks for your kind words about the package. About your questions 

1. The MCMC samplers can use parallelization, but BT will not automatically switch on parallelization because it is not clear to us if model calls are parallelizable (quite a few people use file input output for the model calls). Therefore, usually only one core is used (maybe you see 2 cores because one is for R and one for the dll, although R shouldn't have to do things while the dll is running). If you are confident that your likelihood is parallelizable, you can set parallel = T in the createBayesianSetup. Also note the parallelOptions if you want to control the numbers of cores used. If parallel is on, DREAMzs should make use of it, and this should result in the parallelization of the 3 internal chains that are the default of DREAMzs. Note that the nrChains argument is not parallelized, but can be parallelized by hand, see https://github.com/florianhartig/BayesianTools/issues/9

2. Yes, I know that this is a bit confusing. We have discussed several times how to better present this to the user, but haven't really found a good solution. First of all, it's a fixed property of the DE / DREAM family that they have several internal chains, so this must have also been like this in the Matlab package that you used (btw., how did they handle this?). Secondly, the chains are technically not independent (because proposals are created from z Matrix, and this is fed from the chains), and we do not recommend running Gelman-Diagnostics on a single chain, but it is common in literature, and I think this is supported by a paper by Cajo ter Braak, which shows that the internal chains are asymptotically independent (because, as the Z matrix fills up, it stabilizes and basically becomes the posterior). Thus, once the sampler is in equilibrium, the internal chains are quasi-independent. 

3. I guess not, but what do you want to control?

4. Burn-in should be ignored. In BT, you can pass on the same arguments as in getSample, so just use start = X. About the number of iterations: I don't think there is a formal minimum, but common sense suggests that you can't expect stable values for less than a few hundred iterations. The diagnostics fluctuates with the sampler, so if you have bad mixing, it can fluctuate strongly over time, which is also a motivation to look at the plots.

**Comment by woodwards** [comment]
1. Ok, I can see the 7 R processes in Task Manager, but not much activity on CPU use (about 30% utilization), maybe the CPU use just isn't very heavy.

2. The (master version) Matlab version of DREAM_ZS did have 3 (or more) chains and calculated the Gelman-Rubin statistic on them. It didn't provide functionality for multiple sets of chains.

3. I wanted to suppress the correlation matrix.

Thanks so much for your help. I am gong to be using this package a lot!

**Comment by woodwards** [comment]
Hi Florian

Thank you again for your marvelous package!

I am having some problems with memory errors, I think because my model is a 32 bit Fortran DLL so I need to use 32 bit R (there is some bug in RStudio which prevents me from using a 64-bit DLL and 64 bit R).

I was wondering if you could help me understand how to minimize the size of the mcmcSamplerList object output from runMCMC(DREAMzs). It works if I have burnin=0 and I can repeatedly called runMCMC() with the results until convergence is satisfactory, but it returns the whole sample list which is huge (5Gb) and causes R to crash when I try to work with it.

How can I make it discard the burnin iterations, especially when I am calling runMCMC() multiple times?

Thanks

S

Simon Woodward
Senior Scientist (Mathematical Modelling)
DairyNZ
Cnr Ruakura & Morrinsville Roads | Newstead | Private Bag 3221| Hamilton 3240 | NEW ZEALAND
Ph +64 7 858 3750 | DDI +64 7 858 3787 | Fax +64 7 858 3751
Web www.dairynz.co.nz<http://www.dairynz.co.nz/> | www.GoDairy.co.nz<http://www.godairy.co.nz/> | www.getfresh.co.nz<http://www.getfresh.co.nz/>

**Comment by florianhartig** [comment]
Hi Simon,

the DE sampler family allows setting a burnin and thinning interval to avoid this problem. See ? DREAMzs

```
burnin | number of iterations treated as burn-in. These iterations are not recorded in the chain.
thin | thin thinning parameter. Determines the interval in which values are recorded.
```

Best,
F

**Comment by woodwards** [comment]
Thanks Florian

I’m having trouble with burnin not working correctly. A small point is that the burnin= setting seems to be interpreted incorrectly (I get the wrong number of samples returned); also if I continue/rerun runMCMC() with the results of a previous run that used burnin I get an error, I assume because there are posterior samples outside the prior range?

Error in if (any(x < lower)) return(-Inf) : 
  missing value where TRUE/FALSE needed

Thanks so much

Simon

**Comment by florianhartig** [comment]
hmm ... in principle the burnin works for me, try e.g. 

```
setup = createBayesianSetup(ll, lower = c(-10,-10), upper = c(10,10))
settings = list(nrChains = 2, iterations = 2000, burnin = 1000)
out <- runMCMC(bayesianSetup = setup, sampler = "DREAMzs", settings = settings)
summary(out)
```

a small glitch is that the resulting chain displays as if it was run with 1000 iterations, i.e. the burnin in the beginning really disappears from the chain - maybe we should change this, but it doesn't really affect the functionality. 

However, it's true that there is a bug when trying to restart this with a burnin - I'll file this as an extra issue. Can you work without a restart at the moment?

**Comment by woodwards** [comment]
I had to adjust burnin slightly to get the right number of samples returned

```
bt_settings <- list(startValue=nInternal, 
                    iterations=nChain/nChains, 
                    nrChains=nChains, 
                    burnin=nBurnin/nChains+nChains, 
                    parallel=TRUE,
                    message=TRUE) 

```
I might have a quick look at the runMCMC code and see if I can fix see the problem
