### ISSUE TITLE
runMCMC crashes when burnin>0

### ISSUE THREAD

**Issue by woodwards** [florianhartig/BayesianTools#90]
When I specify burnin>0 in settings, I get the following error after the chains have finished:

(I am using 2 chains of DREAMzs, with 3 internal chains)

```
runMCMC terminated after 81.0899999999965seconds
3000 . Current logp  -204.848 -204.0914 -396.3057 Please wait!  runMCMC terminated after 83.739999999998seconds
 3000 . Current logp  -203.6125 -212.057 -204.4864 Please wait!  Error in chol.default(W) : 
  the leading minor of order 54 is not positive definite
```

**Comment by florianhartig** [comment]
I cannot reproduce this with a simple model, and it also seems odd, because the output looks as if the first chain finishes, and the second then throws an error. 

The error message

`Error in chol.default(W) : the leading minor of order 54 is not positive definite `

usually means that the covariance matrix doesn't have full rank (i.e. a covariance calculation is performed on a chain with one parameter that hasn't moved), so it could be the result of a very short chain that create an error in some internal calculations of the DREAMzs.

If you can, could you post a reproducible example, or failing that, at least your function call, so that I can see how many iterations you have etc.?

**Comment by woodwards** [comment]
If I use burnin>0, how do I get the correct gelman plots, since the burnin section of the chain is discarded.

**Comment by florianhartig** [comment]
It's not very explicit in the documentation, but nearly all functions in BT that act on a MCMC output allow to specify all arguments that go to getSample via the ... argument. So yes, plots and Gelman diagnostics do accept the start argument. 

Maybe the word "burnin" in the runMCMC is even slightly misleading, as you can of course not be sure that the sampler has indeed burned in when setting this argument up, so you have to check again visually, and possibly throw away some samples.

The only purpose of this argument is to avoid using too much memory in case of a long burnin, so what the burnin argument effectively does is starting later with recording the chain. If you have no memory problem, I would just record the whole MCMC, and decide on burnin later based on visual inspection of the chains.
